# Generated by Django 3.2 on 2021-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_bookedlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedlisting',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookedlisting',
            name='check_out',
            field=models.DateField(),
        ),
    ]
